name: cloud-dev

services:
  web:
    container_name: web-app-dev
    build:
      context: ./web
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
