name: cloud-prod

services:
  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - WEB_SERVICE_URL=${WEB_SERVICE_URL}
    depends_on:
      - web

  web:
    container_name: web-app-prod
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
