
name: cloud

services:
  web:
    container_name: cloud_web
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cache
    restart: unless-stopped

  database:
    container_name: cloud_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - "5432:5432"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    container_name: cloud_redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_LOCATION}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: